from Strategies.AMDOpenAggressiveTestingStrategy.TestStrategyBotBuilderV2 import create_bots as AMDOpenAggressiveTestingStrategyCreateBotV2

BOTS_MAPPING = {"AMDOpenAggressiveTestingStrategyCreateBotV2": AMDOpenAggressiveTestingStrategyCreateBotV2}

BOTS_OFFLINE_MAPPING = {"AMDOpenAggressiveTestingStrategyCreateBotV2": AMDOpenAggressiveTestingStrategyCreateBotV2}